IMAGENET_IMAGES_PATH = ''
INTERPOLATION_METHOD = 'INTER_AREA'
NUM_OF_NEIGHBOURS_REBALANCING = 1
NUM_OF_NEIGHBOURS = 5
SMOOTHING_SIGMA = 5
REBALANCING_GAMMA = 0.5
IMG_ROWS, IMG_COLS = 256, 256
BATCH_SIZE = 64