IMAGENET_IMAGES_PATH = 'images/imagenette2-320/images'
IMG_ROWS, IMG_COLS = 256, 256
INTERPOLATION_METHOD = 'INTER_AREA'

NUM_OF_NEIGHBOURS_REBALANCING = 1
NUM_OF_NEIGHBOURS = 10
SMOOTHING_SIGMA = 5
REBALANCING_GAMMA = 0.5


IMAGE_TRAIN_PATH= './images/imagenette2-320/train_names.txt'
IMAGE_VALID_PATH= './images/imagenette2-320/valid_names.txt'


PATIENCE=24
EPOCHS=240
BATCH_SIZE = 128
TRAINING_SAMPLES = 13823
VALIDATION_SAMPLES = 193git 
WEIGTH_DECAY = 1e-3
EPSILON = 1e-8
NB_NEIGHBORS = 5
# temperature parameter T
T = 0.38
