IMAGENET_IMAGES_PATH = './images/imagenet_subset'
TRAIN_NAMES_PATH = 'train_names.txt'
VALID_NAMES_PATH = 'valid_names.txt'
IMG_ROWS, IMG_COLS = 256, 256
INTERPOLATION_METHOD = 'INTER_AREA'

NUM_OF_NEIGHBOURS_REBALANCING = 1
NUM_OF_NEIGHBOURS = 5
SMOOTHING_SIGMA = 5
REBALANCING_GAMMA = 0.5


PATIENCE=8
EPOCHS=40
BATCH_SIZE = 42
TRAINING_SAMPLES = 176691
VALIDATION_SAMPLES = 1425
WEIGTH_DECAY = 1e-3
EPSILON = 1e-8
NB_NEIGHBORS = 5
# temperature parameter T
T = 0.38
